/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdditionalData from './AdditionalData';

/**
 * The CancelPaymentRequest model module.
 * @module model/CancelPaymentRequest
 * @version 1.0.0
 */
class CancelPaymentRequest {
    /**
     * Constructs a new <code>CancelPaymentRequest</code>.
     * Contains the details of the request message
     * @alias module:model/CancelPaymentRequest
     */
    constructor() { 
        
        CancelPaymentRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CancelPaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CancelPaymentRequest} obj Optional instance to populate.
     * @return {module:model/CancelPaymentRequest} The populated <code>CancelPaymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CancelPaymentRequest();

            if (data.hasOwnProperty('additional_data')) {
                obj['additional_data'] = AdditionalData.constructFromObject(data['additional_data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CancelPaymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CancelPaymentRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `additional_data`
        if (data['additional_data']) { // data not null
          AdditionalData.validateJSON(data['additional_data']);
        }

        return true;
    }


}



/**
 * @member {module:model/AdditionalData} additional_data
 */
CancelPaymentRequest.prototype['additional_data'] = undefined;






export default CancelPaymentRequest;

