/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DataField from './DataField';

/**
 * The Data model module.
 * @module model/Data
 * @version 1.0.0
 */
class Data {
    /**
     * Constructs a new <code>Data</code>.
     * Set of data contained in additional_data_list.
     * @alias module:model/Data
     */
    constructor() { 
        
        Data.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Data</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Data} obj Optional instance to populate.
     * @return {module:model/Data} The populated <code>Data</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Data();

            if (data.hasOwnProperty('data_field')) {
                obj['data_field'] = ApiClient.convertToType(data['data_field'], [DataField]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Data</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Data</code>.
     */
    static validateJSON(data) {
        if (data['data_field']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data_field'])) {
                throw new Error("Expected the field `data_field` to be an array in the JSON data but got " + data['data_field']);
            }
            // validate the optional field `data_field` (array)
            for (const item of data['data_field']) {
                DataField.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * A name/value pair which represents a data field
 * @member {Array.<module:model/DataField>} data_field
 */
Data.prototype['data_field'] = undefined;






export default Data;

