/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FeesAmount model module.
 * @module model/FeesAmount
 * @version 1.0.0
 */
class FeesAmount {
    /**
     * Constructs a new <code>FeesAmount</code>.
     * Contains the fees amount for the transaction (actual or proposed), in sender&#39;s currency.
     * @alias module:model/FeesAmount
     */
    constructor() { 
        
        FeesAmount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FeesAmount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeesAmount} obj Optional instance to populate.
     * @return {module:model/FeesAmount} The populated <code>FeesAmount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeesAmount();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FeesAmount</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FeesAmount</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}



/**
 * This parameter contains the transaction fees amount for the transaction.  It holds a decimal number with a maximum length of 18 and a minimum length of 1..
 * @member {String} amount
 */
FeesAmount.prototype['amount'] = undefined;

/**
 * This parameter contains the three-letter \"ISO 4217\" currency code representing the currency for the fees amount for the transaction.   It holds a string of alphabet characters with an exact length of three.
 * @member {String} currency
 */
FeesAmount.prototype['currency'] = undefined;






export default FeesAmount;

