/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Proposal from './Proposal';

/**
 * The Proposals model module.
 * @module model/Proposals
 * @version 1.0.0
 */
class Proposals {
    /**
     * Constructs a new <code>Proposals</code>.
     * The Proposal resource describes a payment proposal, including fees, received amount,fx rates, etc
     * @alias module:model/Proposals
     */
    constructor() { 
        
        Proposals.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Proposals</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Proposals} obj Optional instance to populate.
     * @return {module:model/Proposals} The populated <code>Proposals</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Proposals();

            if (data.hasOwnProperty('proposal')) {
                obj['proposal'] = ApiClient.convertToType(data['proposal'], [Proposal]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Proposals</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Proposals</code>.
     */
    static validateJSON(data) {
        if (data['proposal']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['proposal'])) {
                throw new Error("Expected the field `proposal` to be an array in the JSON data but got " + data['proposal']);
            }
            // validate the optional field `proposal` (array)
            for (const item of data['proposal']) {
                Proposal.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Proposal>} proposal
 */
Proposals.prototype['proposal'] = undefined;






export default Proposals;

