/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Quote from './Quote';

/**
 * The QuoteWrapper model module.
 * @module model/QuoteWrapper
 * @version 1.0.0
 */
class QuoteWrapper {
    /**
     * Constructs a new <code>QuoteWrapper</code>.
     * @alias module:model/QuoteWrapper
     */
    constructor() { 
        
        QuoteWrapper.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QuoteWrapper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuoteWrapper} obj Optional instance to populate.
     * @return {module:model/QuoteWrapper} The populated <code>QuoteWrapper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuoteWrapper();

            if (data.hasOwnProperty('quote')) {
                obj['quote'] = Quote.constructFromObject(data['quote']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuoteWrapper</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuoteWrapper</code>.
     */
    static validateJSON(data) {
        // validate the optional field `quote`
        if (data['quote']) { // data not null
          Quote.validateJSON(data['quote']);
        }

        return true;
    }


}



/**
 * @member {module:model/Quote} quote
 */
QuoteWrapper.prototype['quote'] = undefined;






export default QuoteWrapper;

