/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdditionalData from './AdditionalData';
import PaymentAmount from './PaymentAmount';
import QuoteType from './QuoteType';

/**
 * The QuoteRequest model module.
 * @module model/QuoteRequest
 * @version 1.0.0
 */
class QuoteRequest {
    /**
     * Constructs a new <code>QuoteRequest</code>.
     * Contains the details of the request message.
     * @alias module:model/QuoteRequest
     * @param transactionReference {String} This parameter contains the client-provided unique reference number of the transaction. This value will be utilized as the transaction_reference ID of the payment if a consumer decides to move forward with a payment using the submitted quote. The string held must be unique per transaction.  This parameter holds a string of alphanumeric special characters with a maximum length of 40 and a minimum length of 1. 
     * @param senderAccountUri {String} For all transactions, including nested payments, the Sender Account URI scheme is a mandatory parameter based on the account that is initiating the transaction and must contain the ultimate sender's unique account details for the actual mobile wallet, ewallet, account identifier, bank account or card that is initiating the transaction.  Accordingly, this field should not include a blanket or general account managed by the Debtor Agent.   It holds a string of alphanumeric special characters with a maximum length of 200 and a minimum length of 1.  
     * @param recipientAccountUri {String} This parameter contains the URI identifying a beneficiary's account to receive the payment.   Note that in this parameter, when using the \"pan\" scheme, the \"exp\" property is optional.  It holds a string of alphanumeric special characters with a maximum length of 200 and a minimum length of 1. Refer to the \"Recipient Account URI\" section on \"Additional Resources\" page for details about scheme specific data.
     * @param paymentAmount {module:model/PaymentAmount} 
     * @param paymentOriginationCountry {String} This parameter contains the three-letter \"ISO 3166-1 alpha-3\" country code representing the country in which the payment is being initiated.  It holds a string of alphabet characters with an exact length of three.
     * @param paymentType {String} This parameter contains the three-digit code for the type of transaction that is being submitted. Available types and their uses are provided below:  B2P: Business Disbursement to Person - A disbursement of funds from a business to an individual account.  B2B: Business to Business- A transfer of funds from one business to another.  G2P: Government to Person - A disbursement of funds from a government agency to a private individual person's account.  P2P: Person to Person - A transfer of funds from one private individual person's account to another private individual person's account.  P2B: Person to Business - A payment by an individual person to a business   It holds a string of alphabet characters with an exact length of three. 
     */
    constructor(transactionReference, senderAccountUri, recipientAccountUri, paymentAmount, paymentOriginationCountry, paymentType) { 
        
        QuoteRequest.initialize(this, transactionReference, senderAccountUri, recipientAccountUri, paymentAmount, paymentOriginationCountry, paymentType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transactionReference, senderAccountUri, recipientAccountUri, paymentAmount, paymentOriginationCountry, paymentType) { 
        obj['transaction_reference'] = transactionReference;
        obj['sender_account_uri'] = senderAccountUri;
        obj['recipient_account_uri'] = recipientAccountUri;
        obj['payment_amount'] = paymentAmount;
        obj['payment_origination_country'] = paymentOriginationCountry;
        obj['payment_type'] = paymentType;
    }

    /**
     * Constructs a <code>QuoteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuoteRequest} obj Optional instance to populate.
     * @return {module:model/QuoteRequest} The populated <code>QuoteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuoteRequest();

            if (data.hasOwnProperty('transaction_reference')) {
                obj['transaction_reference'] = ApiClient.convertToType(data['transaction_reference'], 'String');
            }
            if (data.hasOwnProperty('sender_account_uri')) {
                obj['sender_account_uri'] = ApiClient.convertToType(data['sender_account_uri'], 'String');
            }
            if (data.hasOwnProperty('recipient_account_uri')) {
                obj['recipient_account_uri'] = ApiClient.convertToType(data['recipient_account_uri'], 'String');
            }
            if (data.hasOwnProperty('payment_amount')) {
                obj['payment_amount'] = PaymentAmount.constructFromObject(data['payment_amount']);
            }
            if (data.hasOwnProperty('payment_origination_country')) {
                obj['payment_origination_country'] = ApiClient.convertToType(data['payment_origination_country'], 'String');
            }
            if (data.hasOwnProperty('payment_type')) {
                obj['payment_type'] = ApiClient.convertToType(data['payment_type'], 'String');
            }
            if (data.hasOwnProperty('quote_type')) {
                obj['quote_type'] = QuoteType.constructFromObject(data['quote_type']);
            }
            if (data.hasOwnProperty('bank_code')) {
                obj['bank_code'] = ApiClient.convertToType(data['bank_code'], 'String');
            }
            if (data.hasOwnProperty('additional_data')) {
                obj['additional_data'] = AdditionalData.constructFromObject(data['additional_data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuoteRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuoteRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuoteRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['transaction_reference'] && !(typeof data['transaction_reference'] === 'string' || data['transaction_reference'] instanceof String)) {
            throw new Error("Expected the field `transaction_reference` to be a primitive type in the JSON string but got " + data['transaction_reference']);
        }
        // ensure the json data is a string
        if (data['sender_account_uri'] && !(typeof data['sender_account_uri'] === 'string' || data['sender_account_uri'] instanceof String)) {
            throw new Error("Expected the field `sender_account_uri` to be a primitive type in the JSON string but got " + data['sender_account_uri']);
        }
        // ensure the json data is a string
        if (data['recipient_account_uri'] && !(typeof data['recipient_account_uri'] === 'string' || data['recipient_account_uri'] instanceof String)) {
            throw new Error("Expected the field `recipient_account_uri` to be a primitive type in the JSON string but got " + data['recipient_account_uri']);
        }
        // validate the optional field `payment_amount`
        if (data['payment_amount']) { // data not null
          PaymentAmount.validateJSON(data['payment_amount']);
        }
        // ensure the json data is a string
        if (data['payment_origination_country'] && !(typeof data['payment_origination_country'] === 'string' || data['payment_origination_country'] instanceof String)) {
            throw new Error("Expected the field `payment_origination_country` to be a primitive type in the JSON string but got " + data['payment_origination_country']);
        }
        // ensure the json data is a string
        if (data['payment_type'] && !(typeof data['payment_type'] === 'string' || data['payment_type'] instanceof String)) {
            throw new Error("Expected the field `payment_type` to be a primitive type in the JSON string but got " + data['payment_type']);
        }
        // validate the optional field `quote_type`
        if (data['quote_type']) { // data not null
          QuoteType.validateJSON(data['quote_type']);
        }
        // ensure the json data is a string
        if (data['bank_code'] && !(typeof data['bank_code'] === 'string' || data['bank_code'] instanceof String)) {
            throw new Error("Expected the field `bank_code` to be a primitive type in the JSON string but got " + data['bank_code']);
        }
        // validate the optional field `additional_data`
        if (data['additional_data']) { // data not null
          AdditionalData.validateJSON(data['additional_data']);
        }

        return true;
    }


}

QuoteRequest.RequiredProperties = ["transaction_reference", "sender_account_uri", "recipient_account_uri", "payment_amount", "payment_origination_country", "payment_type"];

/**
 * This parameter contains the client-provided unique reference number of the transaction. This value will be utilized as the transaction_reference ID of the payment if a consumer decides to move forward with a payment using the submitted quote. The string held must be unique per transaction.  This parameter holds a string of alphanumeric special characters with a maximum length of 40 and a minimum length of 1. 
 * @member {String} transaction_reference
 */
QuoteRequest.prototype['transaction_reference'] = undefined;

/**
 * For all transactions, including nested payments, the Sender Account URI scheme is a mandatory parameter based on the account that is initiating the transaction and must contain the ultimate sender's unique account details for the actual mobile wallet, ewallet, account identifier, bank account or card that is initiating the transaction.  Accordingly, this field should not include a blanket or general account managed by the Debtor Agent.   It holds a string of alphanumeric special characters with a maximum length of 200 and a minimum length of 1.  
 * @member {String} sender_account_uri
 */
QuoteRequest.prototype['sender_account_uri'] = undefined;

/**
 * This parameter contains the URI identifying a beneficiary's account to receive the payment.   Note that in this parameter, when using the \"pan\" scheme, the \"exp\" property is optional.  It holds a string of alphanumeric special characters with a maximum length of 200 and a minimum length of 1. Refer to the \"Recipient Account URI\" section on \"Additional Resources\" page for details about scheme specific data.
 * @member {String} recipient_account_uri
 */
QuoteRequest.prototype['recipient_account_uri'] = undefined;

/**
 * @member {module:model/PaymentAmount} payment_amount
 */
QuoteRequest.prototype['payment_amount'] = undefined;

/**
 * This parameter contains the three-letter \"ISO 3166-1 alpha-3\" country code representing the country in which the payment is being initiated.  It holds a string of alphabet characters with an exact length of three.
 * @member {String} payment_origination_country
 */
QuoteRequest.prototype['payment_origination_country'] = undefined;

/**
 * This parameter contains the three-digit code for the type of transaction that is being submitted. Available types and their uses are provided below:  B2P: Business Disbursement to Person - A disbursement of funds from a business to an individual account.  B2B: Business to Business- A transfer of funds from one business to another.  G2P: Government to Person - A disbursement of funds from a government agency to a private individual person's account.  P2P: Person to Person - A transfer of funds from one private individual person's account to another private individual person's account.  P2B: Person to Business - A payment by an individual person to a business   It holds a string of alphabet characters with an exact length of three. 
 * @member {String} payment_type
 */
QuoteRequest.prototype['payment_type'] = undefined;

/**
 * @member {module:model/QuoteType} quote_type
 */
QuoteRequest.prototype['quote_type'] = undefined;

/**
 * This parameter contains the bank code associated with the bank name and bank identifier code (BIC) provided by the customer. This parameter is required only for specific bank service provider endpoints identified as part of corridor data details.  It's a conditional parameter that holds alphanumeric special characters with a maximum length of 225 and a minimum length of 1.
 * @member {String} bank_code
 */
QuoteRequest.prototype['bank_code'] = undefined;

/**
 * @member {module:model/AdditionalData} additional_data
 */
QuoteRequest.prototype['additional_data'] = undefined;






export default QuoteRequest;

