/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Tiers from './Tiers';

/**
 * The Rate model module.
 * @module model/Rate
 * @version 1.0.0
 */
class Rate {
    /**
     * Constructs a new <code>Rate</code>.
     * See child attributes
     * @alias module:model/Rate
     */
    constructor() { 
        
        Rate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Rate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Rate} obj Optional instance to populate.
     * @return {module:model/Rate} The populated <code>Rate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Rate();

            if (data.hasOwnProperty('partner_id')) {
                obj['partner_id'] = ApiClient.convertToType(data['partner_id'], 'String');
            }
            if (data.hasOwnProperty('event_type')) {
                obj['event_type'] = ApiClient.convertToType(data['event_type'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('use')) {
                obj['use'] = ApiClient.convertToType(data['use'], 'String');
            }
            if (data.hasOwnProperty('from_currency_code')) {
                obj['from_currency_code'] = ApiClient.convertToType(data['from_currency_code'], 'String');
            }
            if (data.hasOwnProperty('to_currency_code')) {
                obj['to_currency_code'] = ApiClient.convertToType(data['to_currency_code'], 'String');
            }
            if (data.hasOwnProperty('valid_from')) {
                obj['valid_from'] = ApiClient.convertToType(data['valid_from'], 'String');
            }
            if (data.hasOwnProperty('valid_to')) {
                obj['valid_to'] = ApiClient.convertToType(data['valid_to'], 'String');
            }
            if (data.hasOwnProperty('account_type')) {
                obj['account_type'] = ApiClient.convertToType(data['account_type'], 'String');
            }
            if (data.hasOwnProperty('tier_identifier_rate')) {
                obj['tier_identifier_rate'] = ApiClient.convertToType(data['tier_identifier_rate'], 'String');
            }
            if (data.hasOwnProperty('tiers')) {
                obj['tiers'] = Tiers.constructFromObject(data['tiers']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Rate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Rate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['partner_id'] && !(typeof data['partner_id'] === 'string' || data['partner_id'] instanceof String)) {
            throw new Error("Expected the field `partner_id` to be a primitive type in the JSON string but got " + data['partner_id']);
        }
        // ensure the json data is a string
        if (data['event_type'] && !(typeof data['event_type'] === 'string' || data['event_type'] instanceof String)) {
            throw new Error("Expected the field `event_type` to be a primitive type in the JSON string but got " + data['event_type']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['use'] && !(typeof data['use'] === 'string' || data['use'] instanceof String)) {
            throw new Error("Expected the field `use` to be a primitive type in the JSON string but got " + data['use']);
        }
        // ensure the json data is a string
        if (data['from_currency_code'] && !(typeof data['from_currency_code'] === 'string' || data['from_currency_code'] instanceof String)) {
            throw new Error("Expected the field `from_currency_code` to be a primitive type in the JSON string but got " + data['from_currency_code']);
        }
        // ensure the json data is a string
        if (data['to_currency_code'] && !(typeof data['to_currency_code'] === 'string' || data['to_currency_code'] instanceof String)) {
            throw new Error("Expected the field `to_currency_code` to be a primitive type in the JSON string but got " + data['to_currency_code']);
        }
        // ensure the json data is a string
        if (data['valid_from'] && !(typeof data['valid_from'] === 'string' || data['valid_from'] instanceof String)) {
            throw new Error("Expected the field `valid_from` to be a primitive type in the JSON string but got " + data['valid_from']);
        }
        // ensure the json data is a string
        if (data['valid_to'] && !(typeof data['valid_to'] === 'string' || data['valid_to'] instanceof String)) {
            throw new Error("Expected the field `valid_to` to be a primitive type in the JSON string but got " + data['valid_to']);
        }
        // ensure the json data is a string
        if (data['account_type'] && !(typeof data['account_type'] === 'string' || data['account_type'] instanceof String)) {
            throw new Error("Expected the field `account_type` to be a primitive type in the JSON string but got " + data['account_type']);
        }
        // ensure the json data is a string
        if (data['tier_identifier_rate'] && !(typeof data['tier_identifier_rate'] === 'string' || data['tier_identifier_rate'] instanceof String)) {
            throw new Error("Expected the field `tier_identifier_rate` to be a primitive type in the JSON string but got " + data['tier_identifier_rate']);
        }
        // validate the optional field `tiers`
        if (data['tiers']) { // data not null
          Tiers.validateJSON(data['tiers']);
        }

        return true;
    }


}



/**
 * This parameter holds a string of alphanumeric special characters with a max length of 35.
 * @member {String} partner_id
 */
Rate.prototype['partner_id'] = undefined;

/**
 * This parameter holds information related to an escalated FX rate or a standard published FX rate.  Valid values:  - CARDFX_PUB - A new FX rate published as part of its scheduled standard publication.  - CARDFX_ESC - One or more FX rates have been escalated resulting in an out of Schedule Push. Only updated FX rates are provided.   Note: Out of Schedule push rates are sent on rare occasions when a typical market fluctuations exist.
 * @member {String} event_type
 */
Rate.prototype['event_type'] = undefined;

/**
 * This parameter indicates whether the FX rate is tiered or single. Only specially configured Customers will have tiered rates provided; Single is standard.   Valid values :   - tiered   - single  
 * @member {String} type
 */
Rate.prototype['type'] = undefined;

/**
 * Indicates the intended use of this FX rate, i.e. Rate used for the Customer Managed Sender Pricing or Mastercard Managed Sender Pricing. This is based on the business model of the participating Customer.   Customer Managed Sender Pricing = CMSP  Mastercard Managed Sender Pricing = MMSP  Valid values:  - CMSP  - MMSP
 * @member {String} use
 */
Rate.prototype['use'] = undefined;

/**
 * This parameter contains a \"FROM\" currency code in three-letter \"ISO 4217\". This is the sending currency.  It holds a string of alphabet characters with an exact length of three.
 * @member {String} from_currency_code
 */
Rate.prototype['from_currency_code'] = undefined;

/**
 * This parameter contains a \"TO\" currency code in three-letter \"ISO 4217\". This is the beneficiary currency.  It holds a string of alphabet characters with an exact length of three.
 * @member {String} to_currency_code
 */
Rate.prototype['to_currency_code'] = undefined;

/**
 * This parameter contains the effective \"FROM\" date/time and indicates when the FX rate becomes valid.  It holds an \"ISO 8601\" timestamp of the format: \"YYYY-MM-DDTHH:MM:SSZ\"
 * @member {String} valid_from
 */
Rate.prototype['valid_from'] = undefined;

/**
 * This parameter contains the \"TO\" date/time for this FX rate and indicates when the FX rate becomes expired. It holds an \"ISO 8601\" timestamp of the format: \"YYYY-MM-DDTHH:MM:SSZ\"  NOTE: If there are any delays receiving updated rates, Customers utilizing the Expired Rates feature should continue to utilize expired rates until they receive new rates.
 * @member {String} valid_to
 */
Rate.prototype['valid_to'] = undefined;

/**
 * Identification of the beneficiary account type this rate should be used for. Rates can be different based on the beneficiary account type.  Valid values:  - BANK  - E-WALLET  - CARD  - CASH-OUT
 * @member {String} account_type
 */
Rate.prototype['account_type'] = undefined;

/**
 * NOTE: This is applicable for future use only; the value will not be provided, and the field will be blank.  Contains the reference rate that should be used to select the tier of the rate. Amounts in tiers are always provided in \"FROM\" currency. The provided rate should be used to calculate the beneficiary amount, then that beneficiary amount will be used to select the appropriate Tier.   This is only applicable if OI is configured for tiered rates. The format for this value is up to 10 numbers to the left of the decimal and 10 numbers to the right of the decimal. 
 * @member {String} tier_identifier_rate
 */
Rate.prototype['tier_identifier_rate'] = undefined;

/**
 * @member {module:model/Tiers} tiers
 */
Rate.prototype['tiers'] = undefined;






export default Rate;

