/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import GovernmentIds from './GovernmentIds';

/**
 * The Recipient model module.
 * @module model/Recipient
 * @version 1.0.0
 */
class Recipient {
    /**
     * Constructs a new <code>Recipient</code>.
     * Recipient name and address information.
     * @alias module:model/Recipient
     */
    constructor() { 
        
        Recipient.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Recipient</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Recipient} obj Optional instance to populate.
     * @return {module:model/Recipient} The populated <code>Recipient</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Recipient();

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('organization_name')) {
                obj['organization_name'] = ApiClient.convertToType(data['organization_name'], 'String');
            }
            if (data.hasOwnProperty('nationality')) {
                obj['nationality'] = ApiClient.convertToType(data['nationality'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('government_ids')) {
                obj['government_ids'] = ApiClient.convertToType(data['government_ids'], [GovernmentIds]);
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Recipient</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Recipient</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['middle_name'] && !(typeof data['middle_name'] === 'string' || data['middle_name'] instanceof String)) {
            throw new Error("Expected the field `middle_name` to be a primitive type in the JSON string but got " + data['middle_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['organization_name'] && !(typeof data['organization_name'] === 'string' || data['organization_name'] instanceof String)) {
            throw new Error("Expected the field `organization_name` to be a primitive type in the JSON string but got " + data['organization_name']);
        }
        // ensure the json data is a string
        if (data['nationality'] && !(typeof data['nationality'] === 'string' || data['nationality'] instanceof String)) {
            throw new Error("Expected the field `nationality` to be a primitive type in the JSON string but got " + data['nationality']);
        }
        // validate the optional field `address`
        if (data['address']) { // data not null
          Address.validateJSON(data['address']);
        }
        if (data['government_ids']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['government_ids'])) {
                throw new Error("Expected the field `government_ids` to be an array in the JSON data but got " + data['government_ids']);
            }
            // validate the optional field `government_ids` (array)
            for (const item of data['government_ids']) {
                GovernmentIds.validateJsonObject(item);
            };
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}



/**
 * This parameter contains the beneficiary's first name for transactions where the beneficiary is a person. For transactions where the beneficiary is not a person, this field is not allowed.  Note that it is required for transactions where the beneficiary is a person, i.e. the value of quoterequest or paymentrequest.payment_type is B2P, G2P, P2P. Providing this with other payment types will cause an error.  It is a conditional parameter that holds a string of alphanumeric special characters with a maximum length of 140 and a minimum length of 1.
 * @member {String} first_name
 */
Recipient.prototype['first_name'] = undefined;

/**
 * This parameter contains the beneficiary's middle name For transactions where the beneficiary is a person. For transactions where the beneficiary is not a person, this field is not allowed.  Note that this parameter is optional for transactions where the beneficiary is a person, i.e. the value of quoterequest or paymentrequest.payment_type is B2P, G2P, P2P. Providing this with other payment types will cause an error.  It is an optional parameter that holds a string of alphanumeric special characters with a maximum length of 140 and a minimum length of 1.
 * @member {String} middle_name
 */
Recipient.prototype['middle_name'] = undefined;

/**
 * This parameter contains the beneficiary's last name for transactions where the beneficiary is a person. For transactions where the beneficiary is not a person, this field is not allowed.  Note that this parameter is required for transactions where the beneficiary is a person, i.e. the value of quoterequest or paymentrequest.payment_type is B2P, G2P, P2P. Providing this with other payment types will cause an error.  It is a conditional parameter that holds a string of alphanumeric special characters with a maximum length of 140 and a minimum length of 1.
 * @member {String} last_name
 */
Recipient.prototype['last_name'] = undefined;

/**
 * This parameter contains an organization's name for transactions where the beneficiary is not a person. For transactions where the beneficiary is a person, this field is not allowed.  Note that this parameter is required for transactions where the beneficiary is an organization, i.e. the value of quoterequest or paymentrequest.payment_type is B2B, P2B. Providing this with other payment types will cause an error.  It is a conditional parameter that holds a string of alphanumeric special characters with a maximum length of 140 and a minimum length of 1.
 * @member {String} organization_name
 */
Recipient.prototype['organization_name'] = undefined;

/**
 * For transactions where the beneficiary is a person, this is the beneficiary's nationality. This parameter contains the three-letter \"ISO 3166-1 alpha-3\" country code representing beneficiary's nationality. In the case of a business or government organization, this is the registered country of the organization.  It holds a string of alphabet characters with an exact length of three.
 * @member {String} nationality
 */
Recipient.prototype['nationality'] = undefined;

/**
 * @member {module:model/Address} address
 */
Recipient.prototype['address'] = undefined;

/**
 * List of recipient government ids. Note: There can be 0 to many of these fields required and used for each transaction.
 * @member {Array.<module:model/GovernmentIds>} government_ids
 */
Recipient.prototype['government_ids'] = undefined;

/**
 * This parameter contains the phone number of the beneficiary for transactions where the beneficiary is a person. For transactions where the beneficiary is a business/entity, this is the phone number of a contact at the business/entity.  It holds an alphanumeric special value with a maximum length of 30 and a minimum length of 1.<br> The number (usually a MSISDN) must be expressed as an E164 number containing:  [+][country code][area code][local phone number]  '+' - plus sign<br> country code - international country code<br> area code/national destination code - code without leading 0<br> phone number - local phone number  The '+' sign is mandatory (it is compliant with RFC3966 format / international number only). <p>examples :</p>     <table>     <tr>     <td>Country</td>     <td>Local Phone</td>     <td>E.164 Formatted Number</td>     </tr>     <tr>     <td>US</td>     <td>415 123 1234</td>     <td>+14151231234</td>     </tr>     <tr>     <td>UK</td>     <td>020 1234 1234</td>     <td>+442012341234</td>     </tr>     </table>
 * @member {String} phone
 */
Recipient.prototype['phone'] = undefined;

/**
 * For transactions where the beneficiary is a person, this is the email address of the beneficiary. For transactions where the beneficiary is a Business/Entity, this is the email address of a contact at the business/entity.  It holds a string of alphanumeric special characters with a maximum length of 1000 and a minimum length of 5.
 * @member {String} email
 */
Recipient.prototype['email'] = undefined;






export default Recipient;

