/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RejectedStatus model module.
 * @module model/RejectedStatus
 * @version 1.0.0
 */
class RejectedStatus {
    /**
     * Constructs a new <code>RejectedStatus</code>.
     * Object representing the rejection status code and message. This object and it related fields will only  be returned if the payment status is REJECTED.
     * @alias module:model/RejectedStatus
     */
    constructor() { 
        
        RejectedStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RejectedStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RejectedStatus} obj Optional instance to populate.
     * @return {module:model/RejectedStatus} The populated <code>RejectedStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RejectedStatus();

            if (data.hasOwnProperty('Code')) {
                obj['Code'] = ApiClient.convertToType(data['Code'], 'String');
            }
            if (data.hasOwnProperty('Message')) {
                obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RejectedStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RejectedStatus</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Code'] && !(typeof data['Code'] === 'string' || data['Code'] instanceof String)) {
            throw new Error("Expected the field `Code` to be a primitive type in the JSON string but got " + data['Code']);
        }
        // ensure the json data is a string
        if (data['Message'] && !(typeof data['Message'] === 'string' || data['Message'] instanceof String)) {
            throw new Error("Expected the field `Message` to be a primitive type in the JSON string but got " + data['Message']);
        }

        return true;
    }


}



/**
 * This is the numeric code representation of the why the payment request was rejected. Valid values can be found in the \"Error Code\" column of the \"Error Codes\" section of this documentation.  It holds a string of numeric characters with an exact length of 6.
 * @member {String} Code
 */
RejectedStatus.prototype['Code'] = undefined;

/**
 * This is the English text representation of the why the payment request was rejected. Valid values can be found in the \"Error Description\" column of the \"Error Codes\" section of this documentation.  It holds a string of alphanumeric special characters with a maximum length of 1000 and a minimum length of 1.
 * @member {String} Message
 */
RejectedStatus.prototype['Message'] = undefined;






export default RejectedStatus;

