/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Reverse model module.
 * @module model/Reverse
 * @version 1.0.0
 */
class Reverse {
    /**
     * Constructs a new <code>Reverse</code>.
     * @alias module:model/Reverse
     */
    constructor() { 
        
        Reverse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Reverse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Reverse} obj Optional instance to populate.
     * @return {module:model/Reverse} The populated <code>Reverse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Reverse();

            if (data.hasOwnProperty('sender_currency')) {
                obj['sender_currency'] = ApiClient.convertToType(data['sender_currency'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Reverse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Reverse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['sender_currency'] && !(typeof data['sender_currency'] === 'string' || data['sender_currency'] instanceof String)) {
            throw new Error("Expected the field `sender_currency` to be a primitive type in the JSON string but got " + data['sender_currency']);
        }

        return true;
    }


}



/**
 * This parameter contains the three-letter \"ISO 4217\" currency code in which the sender will send the payment. This parameter is required for reverse type.    Note that if no type is used then it defaults to forward type with the fees_included field set to \"true.\" A forward and a reverse type shouldn't be used together. Using forward.fees_included along with reverse.sender_currency throws an error.   It's an optional parameter that holds alphabet characters with an exact length of three 
 * @member {String} sender_currency
 */
Reverse.prototype['sender_currency'] = undefined;






export default Reverse;

