/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RatesWrapper from '../model/RatesWrapper';

/**
* CardedRate service.
* @module api/CardedRateApi
* @version 1.0.0
*/
export default class CardedRateApi {

    /**
    * Constructs a new CardedRateApi. 
    * @alias module:api/CardedRateApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getFxRates operation.
     * @callback module:api/CardedRateApi~getFxRatesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RatesWrapper} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * The Carded Rate APIs are part of an opt-in service that provides FX rates for currency pairs supported by an OI who has opted in to participate in the service. The Carded Rate APIs will provide dealable FX rates, rate IDs, effective times, as well as other information. OIs who have not opted into this service but code to these APIs will not receive rates (Push API) and will receive an error by the system upon submitting a request (Pull API). Refer to the Mastercard Cross-Border Services Product guide for further details on the service.     The FX Rate API - Pull, if used as the primary mechanism to retrieve FX rates, will require the OI to create a scheduler that will call this API based on refresh times per currency pair provided by Mastercard Send.
     * @param {String} partnerId Path Param - This is the Assigned Provider Id. Details- This parameter holds a string of alphanumeric special characters with a maximum length of 35.
     * @param {module:api/CardedRateApi~getFxRatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RatesWrapper}
     */
    getFxRates(partnerId, callback) {
      let postBody = null;
      // verify the required parameter 'partnerId' is set
      if (partnerId === undefined || partnerId === null) {
        throw new Error("Missing the required parameter 'partnerId' when calling getFxRates");
      }

      let pathParams = {
        'partner-id': partnerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RatesWrapper;
      return this.apiClient.callApi(
        '/send/v1/partners/{partner-id}/crossborder/rates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
