/**
 * Crossborder
 * MasterCard Cross-Border Services enables banks in their capacity as Originating Institutions to send cross-border payments for various payment types including person-to-person payments (P2P), person-to-business payments (P2B), business-to-person disbursements (B2P), business-to-business payments (B2B), and government-to-person disbursement (G2P). Mastercard Cross-Border Services supports a variety of payout options, including bank accounts, mobile money accounts, consumer cards, and retail cash pick-up.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Crossborder);
  }
}(this, function(expect, Crossborder) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Crossborder.Rate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Rate', function() {
    it('should create an instance of Rate', function() {
      // uncomment below and update the code to test Rate
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be.a(Crossborder.Rate);
    });

    it('should have the property partnerId (base name: "partner_id")', function() {
      // uncomment below and update the code to test the property partnerId
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property eventType (base name: "event_type")', function() {
      // uncomment below and update the code to test the property eventType
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property use (base name: "use")', function() {
      // uncomment below and update the code to test the property use
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property fromCurrencyCode (base name: "from_currency_code")', function() {
      // uncomment below and update the code to test the property fromCurrencyCode
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property toCurrencyCode (base name: "to_currency_code")', function() {
      // uncomment below and update the code to test the property toCurrencyCode
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property validFrom (base name: "valid_from")', function() {
      // uncomment below and update the code to test the property validFrom
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property validTo (base name: "valid_to")', function() {
      // uncomment below and update the code to test the property validTo
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property accountType (base name: "account_type")', function() {
      // uncomment below and update the code to test the property accountType
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property tierIdentifierRate (base name: "tier_identifier_rate")', function() {
      // uncomment below and update the code to test the property tierIdentifierRate
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

    it('should have the property tiers (base name: "tiers")', function() {
      // uncomment below and update the code to test the property tiers
      //var instance = new Crossborder.Rate();
      //expect(instance).to.be();
    });

  });

}));
